spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        type: trace
    hibernate:
      ddl-auto: validate
    show-sql: true