spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jarkyn
    username: admin
    password: 123qwe123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true

security:
  jwt:
    secret: oV8u8rMyJkhN5f9wM4rF1dpWjwzQ7fCNxsaYPVvgl0xmHiEQk6N8OZ5KSvrPNPMl
    access-ttl-minutes: 900   # 15 минут
    refresh-ttl-minutes: 525600 # 1 год

cloud:
  s3:
    key: minioadmin
    secret: minioadmin
    endpoint: http://localhost:9000
    region: us-east-1


