spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jarkyn
    username: admin
    password: 123qwe123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true

cloud:
  s3:
    key: minioadmin
    secret: minioadmin
    endpoint: http://localhost:9000
    region: us-east-1


